import { test, expect } from '@playwright/test';
import { todayISO } from './helpers/test-utils';

test('T24 - Create a Request', async ({ page }) => {
    await page.goto('http://localhost:3000/');
    await page.getByRole('textbox', { name: 'Email Address' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('moniqueh@vanguard.com');
    await page.getByRole('textbox', { name: 'Password Forgot password?' }).click();
    await page.getByRole('textbox', { name: 'Password Forgot password?' }).fill('Vcat2026!');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByRole('link', { name: 'Tracker' }).click();
    await page.getByRole('button', { name: 'Requests' }).click();
    await page.locator("text=Loading requests...").waitFor({ state: "hidden" });
    await page.getByRole('button', { name: '+ Add Request' }).click();
    await page.getByRole('combobox').selectOption('LOW');
    await page.getByRole('textbox', { name: 'Name' }).click();
    await page.getByRole('textbox', { name: 'Name' }).fill('Test Requester');
    await page.getByRole('textbox').nth(4).fill(todayISO());
    await page.getByRole('textbox', { name: 'Describe the purpose of this' }).click();
    await page.getByRole('textbox', { name: 'Describe the purpose of this' }).fill('Test');
    await page.getByRole('button', { name: 'Create Request' }).click();
});

test("T28 - Add Existing Control Test to Request", async ({ page }) => {
    await page.goto('http://localhost:3000/');
    await page.getByRole('textbox', { name: 'Email Address' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('moniqueh@vanguard.com');
    await page.getByRole('textbox', { name: 'Password Forgot password?' }).click();
    await page.getByRole('textbox', { name: 'Password Forgot password?' }).fill('Vcat2026!');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByRole('link', { name: 'Tracker' }).click();
    await page.getByRole('button', { name: 'Requests' }).click();
    await page.locator("text=Loading requests...").waitFor({ state: "hidden" });
    await page.getByRole('button', { name: '+ Add Request' }).click();
    await page.getByRole('combobox').selectOption('LOW');
    await page.getByRole('textbox', { name: 'Name' }).click();
    await page.getByRole('textbox', { name: 'Name' }).fill('Test Requester');
    await page.getByRole('textbox').nth(4).fill(todayISO());
    await page.getByRole('textbox', { name: 'Describe the purpose of this' }).click();
    await page.getByRole('textbox', { name: 'Describe the purpose of this' }).fill('Test');
    await page.getByRole('button', { name: 'Create Request' }).click();
    const firstRequestCard = page.locator('.requests-list .request-card').first();
    await firstRequestCard.waitFor({ state: 'visible' });
    await firstRequestCard.getByRole('button', { name: 'Details' }).click();
    await page.getByRole('button', { name: 'Edit Request' }).click();
    await page.locator("text=Loading request details...").waitFor({ state: "hidden" });
    await page.getByRole('textbox', { name: 'Search Controls to add...' }).click();
    const firstResult = page.locator('.erm-search-dropdown .erm-search-result-item').first();
    await firstResult.waitFor({ state: 'visible' });
    const firstAddBtn = firstResult.locator('button.erm-add-btn');
    await firstAddBtn.scrollIntoViewIfNeeded();
    await firstAddBtn.click();
    await page.getByRole('button', { name: 'Save Changes' }).click();
});
