export const controlsData = [
  {
    id: 1,
    vgcpid: 'VGCP-100001',
    tester: 'John Smith',
    testType: 'DAT & OET',
    status: 'OET In Progress',
    statusType: 'in-progress',
    step: 'Addressing Comments',
    dateUpdated: 'Jan 14, 2026',
    dueDate: 'Jan 28, 2026',
    etaDate: 'Jan 18, 2026',
  },
  {
    id: 2,
    vgcpid: 'VGCP-100002',
    tester: 'Sarah Johnson',
    testType: 'DAT & OET',
    status: 'Completed',
    statusType: 'completed',
    step: 'Complete',
    dateUpdated: 'Jan 13, 2026',
    dueDate: 'Jan 15, 2026',
    etaDate: 'Jan 15, 2026',
  },
  {
    id: 3,
    vgcpid: 'VGCP-100003',
    tester: 'Michael Chen',
    testType: 'DAT Only',
    status: 'Not Started',
    statusType: 'not-started',
    step: 'Not Started',
    dateUpdated: 'Jan 9, 2026',
    dueDate: 'Jan 22, 2026',
    etaDate: 'Jan 15, 2026',
  },
  {
    id: 4,
    vgcpid: 'VGCP-100004',
    tester: 'David Wilson',
    testType: 'DAT & OET',
    status: 'In Review',
    statusType: 'in-review',
    step: 'Complete',
    dateUpdated: 'Jan 12, 2026',
    dueDate: 'Jan 12, 2026',
    etaDate: 'Jan 12, 2026',
  },
  {
    id: 5,
    vgcpid: 'VGCP-100005',
    tester: 'Lisa Anderson',
    testType: 'DAT Only',
    status: 'Blocked',
    statusType: 'blocked',
    step: 'Testing Blocked',
    dateUpdated: 'Jan 16, 2026',
    dueDate: 'Jan 21, 2026',
    etaDate: 'Jan 21, 2026',
  },
];
