export const controlsData = [
  {
    id: 1,
    vgcpid: 'VGCP-100001',
    tester: 'John Smith',
    testType: 'DAT & OET',
    status: 'OET In Progress',
    statusType: 'in-progress',
    step: 'Addressing Comments',
    dateUpdated: 'Jan 14, 2026',
    dueDate: 'Jan 28, 2026',
    etaDate: 'Jan 18, 2026',
  },
  {
    id: 2,
    vgcpid: 'VGCP-100002',
    tester: 'Sarah Johnson',
    testType: 'DAT & OET',
    status: 'Completed',
    statusType: 'completed',
    step: 'Complete',
    dateUpdated: 'Jan 13, 2026',
    dueDate: 'Jan 15, 2026',
    etaDate: 'Jan 15, 2026',
  },
  {
    id: 3,
    vgcpid: 'VGCP-100003',
    tester: 'Michael Chen',
    testType: 'DAT Only',
    status: 'Not Started',
    statusType: 'not-started',
    step: 'Not Started',
    dateUpdated: 'Jan 9, 2026',
    dueDate: 'Jan 22, 2026',
    etaDate: 'Jan 15, 2026',
  },
  {
    id: 4,
    vgcpid: 'VGCP-100004',
    tester: 'David Wilson',
    testType: 'DAT & OET',
    status: 'In Review',
    statusType: 'in-review',
    step: 'Complete',
    dateUpdated: 'Jan 12, 2026',
    dueDate: 'Jan 12, 2026',
    etaDate: 'Jan 12, 2026',
  },
  {
    id: 5,
    vgcpid: 'VGCP-100005',
    tester: 'Lisa Anderson',
    testType: 'DAT Only',
    status: 'Blocked',
    statusType: 'blocked',
    step: 'Testing Blocked',
    dateUpdated: 'Jan 16, 2026',
    dueDate: 'Jan 21, 2026',
    etaDate: 'Jan 21, 2026',
  },
  {
    id: 6,
    vgcpid: 'VGCP-100006',
    tester: 'Monique Huynh',
    testType: 'DAT & OET',
    status: 'OET In Progress',
    statusType: 'in-progress',
    step: 'Addressing Comments',
    dateUpdated: 'Feb 22, 2026',
    dueDate: 'Mar 3, 2026',
    etaDate: 'Feb 26, 2026',
  },
  {
    id: 7,
    vgcpid: 'VGCP-100007',
    tester: 'Andrew Nguyen',
    testType: 'DAT Only',
    status: 'Not Started',
    statusType: 'not-started',
    step: 'Not Started',
    dateUpdated: 'Feb 23, 2026',
    dueDate: 'Mar 6, 2026',
    etaDate: 'Feb 28, 2026',
  },
  {
    id: 8,
    vgcpid: 'VGCP-100008',
    tester: 'Sarah Johnson',
    testType: 'DAT & OET',
    status: 'In Review',
    statusType: 'in-review',
    step: 'Complete',
    dateUpdated: 'Feb 24, 2026',
    dueDate: 'Mar 7, 2026',
    etaDate: 'Mar 1, 2026',
  },
  {
    id: 9,
    vgcpid: 'VGCP-100009',
    tester: 'John Smith',
    testType: 'DAT Only',
    status: 'Completed',
    statusType: 'completed',
    step: 'Complete',
    dateUpdated: 'Feb 24, 2026',
    dueDate: 'Feb 27, 2026',
    etaDate: 'Feb 24, 2026',
  },
  {
    id: 10,
    vgcpid: 'VGCP-100010',
    tester: 'David Wilson',
    testType: 'DAT & OET',
    status: 'Blocked',
    statusType: 'blocked',
    step: 'Testing Blocked',
    dateUpdated: 'Feb 25, 2026',
    dueDate: 'Mar 8, 2026',
    etaDate: 'Mar 2, 2026',
  },
  {
    id: 11,
    vgcpid: 'VGCP-100011',
    tester: 'Lisa Anderson',
    testType: 'DAT Only',
    status: 'OET In Progress',
    statusType: 'in-progress',
    step: 'Addressing Comments',
    dateUpdated: 'Feb 26, 2026',
    dueDate: 'Mar 10, 2026',
    etaDate: 'Mar 3, 2026',
  },
  {
    id: 12,
    vgcpid: 'VGCP-100012',
    tester: 'Michael Chen',
    testType: 'DAT & OET',
    status: 'Not Started',
    statusType: 'not-started',
    step: 'Not Started',
    dateUpdated: 'Feb 27, 2026',
    dueDate: 'Mar 11, 2026',
    etaDate: 'Mar 5, 2026',
  },
];
